### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Anirudh257**
Added Code link for View Adaptive Neural Networks for Skeleton based Human Action Recognition

### CODE REVIEW

**Comment by cagbal** [comment]
I'll check it this weekend, thanks for your contribution.

**Comment by Anirudh257** [comment]
Thanks, I had some more ideas for improving this repository. We can add proper blog links like this Chinese website: https://www.cnblogs.com/shyern/p/11398185.html. It is a short explanation containing the model diagram and the main contributions of the paper.

**Comment by cagbal** [comment]
Sure any ideas are appreciated. However, I would like to keep it English. So, if you know any good English blog, feel free to send a PR.

**Comment by Anirudh257** [comment]
Yes, it would be in English only :). I was suggesting that along with the accuracies and a short note about the paper, we can include diagrams too to improve the understanding.

**Pull request merged**
