### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Anirudh257**
Added a summary of 2s-AGCN model

### CODE REVIEW

**Comment by cagbal** [comment]
Thanks for your contribution. I'll review it asap.

**Comment by Anirudh257** [comment]
Sure :)

**Comment by cagbal** [comment]
Hi, I checked the paper and have some comments. Sorry, it took a while. 
1. The accuracy is 95.1%, but in your branch, it is shown as 88%. Could you fix this? Or am I missing sth? 
2. Also, the top 2 accuracy table should be changed accordingly. I would appreciate If you can do it.

**Comment by Anirudh257** [comment]
Hi, the accuracy of 2s-AGCN on the **cross-subject protocol** on the NTU-RGB-D dataset is **88.5** % and for the **cross-view protocol** it is **95.1** %. As all the papers in the notes mention only the cross-subject (CS) accuracy, I mentioned only that. This is less than the top-2 accuracies obtained till now.  You can create a table reporting both the cross-subject and cross-setup accuracies.

**Comment by cagbal** [comment]
Haha sorry my bad. I checked it really fast. You are right.  

Cross view will make the repo a bit crowded so lets leave it like this.

**Comment by Anirudh257** [comment]
No problem :). If there are no remaining issues, could you accept this pull request? I wanted to add more paper summaries. :smile:

**Pull request merged**
