### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Anirudh257**
Added the paper: "Skeleton-Based Action Recognition with Directed Graph Neural Networks"

Apologies if my explanation is not good. I am just a beginner trying to grasp the logic behind this topic.

### CODE REVIEW

**Comment by cagbal** [comment]
Thanks! I will check it during the weekend

**Comment by cagbal** [comment]
Hi, just a few comments. One bullet point is too big. Could you make it smaller? 

Also, you wrote " It uses Directed Acyclic Graph (DAG) approach for the first time", but I could not find this statement in the paper. They say novel DAG. We should delete this if there is no statement like that.

**Comment by Anirudh257** [comment]
Sure, I will make the changes.

**Review by Anirudh257 — COMMENTED** [review]
Made the changes according to your comments

**Comment by cagbal** [comment]
Thanks for your contribution.

**Comment by Anirudh257** [comment]
Thanks to you for opening this wonderful repository!! :)

**Pull request merged**
